### PR TITLE
Frontend Improvements, Clean Frontend Code

### PR DESCRIPTION
**Pull request by MarcWebDev**
Added search bar animation & fixed search bar bugs, cleaned up the frontend code & the file structure, added some hover effects

### CODE REVIEW

**Comment by mezotv** [comment]
Looks really cool!

**Review by mezotv — APPROVED** [review]
Code looks good and works

**Comment by nileshkr17** [comment]
Hey @MarcWebDev 
I am planning to optimize this project for different screen resolutions as you can notice that I have added PWA into it.
If you want to contribute to that, I can make raise another issue and assign it to you.
The search bar feature which you have added is amazing but on mobile, it is not working properly
priority is to optimize it for different screen resolutions.
let me know your thoughts 
also if you want to give some suggestions feel free to.🚀

**Comment by MarcWebDev** [comment]
I'm planning to do a full responsive optimization within the next days.

**Comment by nileshkr17** [comment]
> I'm planning to do a full responsive optimization within the next days.

Sounds great!

**Pull request closed without merging**
